#!/usr/bin/env python3
"""
mcp_lab_server: a config-driven MCP server for learning how MCP servers work.

You do not edit this file. You edit a TOML config that declares the server's identity, its tools,
its prompts and its resources, then restart the server. That is the whole point: an MCP server is
mostly a *manifest* plus a little behaviour, and the manifest is what the model actually reads.

    ./mcp_lab_server.py --config examples/looney-tunes-compliance.toml --validate
    ./mcp_lab_server.py --config my-server.toml                       # stdio (for opencode)
    ./mcp_lab_server.py --config my-server.toml --http 0.0.0.0:1491   # HTTP (for curl)

Stdlib only. No dependencies, no build. Python 3.11+ (for tomllib).
"""
import argparse, json, os, re, socket, sys, threading, uuid
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

try:
    import tomllib
except ModuleNotFoundError:                                   # pragma: no cover
    tomllib = None

VERSION = "1.3.0"
PROTOCOL_VERSION = "2025-06-18"

# JSON-RPC 2.0 error codes we use (https://www.jsonrpc.org/specification)
PARSE_ERROR, INVALID_REQUEST, METHOD_NOT_FOUND, INVALID_PARAMS, INTERNAL_ERROR = \
    -32700, -32600, -32601, -32602, -32603


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


# ======================================================================== behaviours
#
# A tool's `behavior` decides what it DOES when called. Everything here is deliberately local and
# self-contained: no network, no database, no backend. The lab is about the protocol and about tool
# descriptions, not about plumbing.

def _arg(args, name, default=""):
    v = args.get(name, default)
    return v if isinstance(v, str) else json.dumps(v)


def b_static(tool, args):
    return tool.get("text", "(this tool has no `text` configured)"), False


def b_echo(tool, args):
    return json.dumps(args, indent=2), False


def b_template(tool, args):
    tpl = tool.get("text", "")
    try:
        return tpl.format(**{k: _arg(args, k) for k in args}), False
    except KeyError as e:
        return f"template referenced {e} but the caller did not supply it", True


def b_forbidden_words(tool, args):
    """The Looney Tunes case: fail if any banned phrase appears in the input."""
    field = tool.get("field", "text")
    words = tool.get("words", [])
    haystack = _arg(args, field)
    cmp = haystack if tool.get("case_sensitive", False) else haystack.lower()
    hits = [w for w in words if (w if tool.get("case_sensitive", False) else w.lower()) in cmp]
    if hits:
        lines = [f"NON-COMPLIANT: {len(hits)} forbidden term(s) found:"]
        lines += [f"  - {w!r} at position {cmp.find(w.lower() if not tool.get('case_sensitive', False) else w)}"
                  for w in hits]
        lines.append(tool.get("fail_message", "Rewrite the text to remove these terms."))
        return "\n".join(lines), bool(tool.get("error_on_fail", False))
    return tool.get("pass_message", "COMPLIANT: no forbidden terms found."), False


def b_required_words(tool, args):
    field, words = tool.get("field", "text"), tool.get("words", [])
    hay = _arg(args, field).lower()
    missing = [w for w in words if w.lower() not in hay]
    if missing:
        return "NON-COMPLIANT, missing required term(s): " + ", ".join(repr(w) for w in missing), \
               bool(tool.get("error_on_fail", False))
    return tool.get("pass_message", "COMPLIANT: all required terms present."), False


def b_regex_check(tool, args):
    field, pattern = tool.get("field", "text"), tool.get("pattern", "")
    try:
        rx = re.compile(pattern, 0 if tool.get("case_sensitive", False) else re.I)
    except re.error as e:
        return f"the `pattern` in this tool's config is not valid regex: {e}", True
    found = rx.findall(_arg(args, field))
    if found and tool.get("expect", "absent") == "absent":
        return f"NON-COMPLIANT, pattern matched {len(found)} time(s): {found[:10]}", \
               bool(tool.get("error_on_fail", False))
    if not found and tool.get("expect", "absent") == "present":
        return "NON-COMPLIANT: required pattern not found.", bool(tool.get("error_on_fail", False))
    return tool.get("pass_message", "COMPLIANT."), False


def b_word_count(tool, args):
    text = _arg(args, tool.get("field", "text"))
    words, chars = len(text.split()), len(text)
    limit = tool.get("max_words")
    verdict = ""
    if limit is not None:
        verdict = f"\nverdict: {'OVER' if words > limit else 'within'} the {limit}-word limit"
    return f"words: {words}\ncharacters: {chars}{verdict}", False


def b_always_error(tool, args):
    """Deliberately fails, so students can see how a client reacts to a tool error."""
    return tool.get("text", "This tool always fails on purpose."), True


# Gravwell modules that condense entries. A raw grep after one of these is not looking at the
# data the author thinks it is.
_AGGREGATORS = {"count", "stats", "sum", "mean", "min", "max", "unique", "table", "chart",
                "text", "raw", "sort", "limit", "first", "last", "fdg", "gauge", "pointmap",
                "heatmap", "stackgraph", "numbercard", "wordcloud", "hexbin", "pcap"}


def _split_pipeline(query):
    """Split a Gravwell query on `|` that are not inside quotes. Returns the segments, stripped."""
    segs, buf, quote = [], [], None
    for ch in query:
        if quote:
            buf.append(ch)
            if ch == quote:
                quote = None
        elif ch in "\'\"":
            quote = ch
            buf.append(ch)
        elif ch == "|":
            segs.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    segs.append("".join(buf).strip())
    return [x for x in segs if x != ""]


def _head_and_first_module(seg0):
    """The first segment carries the tag spec (`tag=x`, `start=`, `end=`, `limit=` …) followed by
    the first module. Split it into (spec words, module words)."""
    words = seg0.split()
    i = 0
    while i < len(words) and re.match(r"^[A-Za-z_]+=", words[i]):
        i += 1
    return words[:i], words[i:]


def _is_raw_grep(module_words):
    """`grep "foo"` is raw: it scans the entry bytes. `grep -e field "foo"` is enumerated: it
    tests an extracted field. Only the raw form is worth hoisting."""
    return bool(module_words) and module_words[0] == "grep" and "-e" not in module_words


def b_gravwell_grep_hoist(tool, args):
    """The query-advisor case. Takes a query that *someone else* has already validated (Gravwell's
    own parse_query tool does that far better than this ever could), and suggests one specific
    improvement: a raw `grep` that sits late in the pipeline should move to the front, where it
    filters entries before any extraction module has to touch them."""
    qfield, pfield = tool.get("query_field", "query"), tool.get("parse_field", "parse_result")
    query = _arg(args, qfield).strip()
    parse_result = _arg(args, pfield).strip()
    if not query:
        return f"no query supplied in `{qfield}`.", True
    if tool.get("require_parse", True):
        if not parse_result:
            return (f"I do not validate queries. Run Gravwell's parse_query on it first and pass "
                    f"that result in `{pfield}`."), True
        if "SUCCESS" not in parse_result.upper():
            return (f"parse_query did not report SUCCESS ({parse_result!r}). Fix the syntax first; "
                    "there is nothing to improve in a query that does not parse."), False
    segs = _split_pipeline(query)
    spec, first = _head_and_first_module(segs[0])
    modules = [first] + [s.split() for s in segs[1:]]        # module words, in pipeline order
    seg_text = [" ".join(first)] + segs[1:]
    raw_late = [i for i, m in enumerate(modules) if i > 0 and _is_raw_grep(m)]
    if not raw_late:
        early = [i for i, m in enumerate(modules) if _is_raw_grep(m)]
        why = ("its only raw grep is already the first module" if early
               else "it has no raw grep; any grep in it uses -e and tests an extracted field")
        return tool.get("pass_message", f"No change suggested: {why}.\n\nquery: {query}"), False
    notes, hoisted, rest = [], [], []
    for i, m in enumerate(modules):
        if i in raw_late:
            hoisted.append(seg_text[i])
            before = [x[0] for x in modules[:i] if x]
            agg = [x for x in before if x in _AGGREGATORS]
            note = (f"module {i + 1} `{seg_text[i]}` scans raw entry bytes but runs after "
                    f"{', '.join('`' + x + '`' for x in before)}; every entry those modules "
                    "processed could have been dropped first.")
            if agg:
                note += (f" It also follows an aggregator (`{agg[0]}`), so it is matching the "
                         "condensed output, not the events.")
            notes.append(note)
        else:
            rest.append(seg_text[i])
    new_first = " ".join(spec + hoisted[:1]).strip()
    pipeline = [new_first] + hoisted[1:] + [x for x in rest if x]
    suggestion = "\n| ".join(pipeline)
    lines = ["SUGGESTION: move the raw grep to the front of the pipeline."] + [f"- {n}" for n in notes]
    lines.append("- A raw grep is the cheapest filter Gravwell has: it drops entries before any "
                 "extraction or aggregation runs. If you meant to match one field, use "
                 "`grep -e <field> <pattern>` right after the module that extracts the field.")
    lines.append("")
    lines.append("suggested query:")
    lines.append(suggestion)
    lines.append("")
    lines.append("Run parse_query on the suggested query before using it; this tool does not check "
                 "syntax.")
    return "\n".join(lines), False


def b_threat_hunt(tool, args):
    """The threat-hunt case, and a deliberate STUB. It stands in for a threat-analysis service whose
    input is raw log entries fetched by another server's tool (Gravwell's execute_query or
    sample_tag_entries). It does no real analysis: it proves the entries arrived, scans them for a
    configurable list of indicator strings, and reports. Building the real analysis behind this
    interface is the take-home exercise."""
    field = tool.get("field", "logs")
    logs = _arg(args, field)
    tag = _arg(args, tool.get("tag_field", "tag"), "") or "unknown"
    source = _arg(args, tool.get("source_field", "source_tool"), "") or "unstated"
    lines = [l for l in logs.splitlines() if l.strip()]
    if not lines:
        return (f"No log data supplied in `{field}`. Retrieve entries first with Gravwell's "
                "execute_query or sample_tag_entries tool and pass their text here verbatim."), True
    indicators = [str(i) for i in tool.get("indicators",
                  ["cherdenko", "krukov", "iron curtain", "vacuum imploder", "kirov", "premier"])]
    hits = [(i, n + 1, l.strip()[:120]) for n, l in enumerate(lines)
            for i in indicators if i.lower() in l.lower()]
    adversary = tool.get("adversary", "APT Cherdenko")
    out = [f"THREAT HUNT REPORT: {adversary}",
           f"entries received: {len(lines)} ({len(logs)} bytes), tag={tag}, fetched by: {source}",
           f"indicators checked: {', '.join(indicators)}",
           f"indicator matches: {len(hits)}"]
    out += [f"  - line {n}: {i!r} in: {l}" for i, n, l in hits[:10]]
    out.append("sample of what arrived (first 3 entries, truncated):")
    out += [f"  {n + 1}. {l.strip()[:120]}" for n, l in enumerate(lines[:3])]
    if hits:
        verdict = tool.get("hit_message",
                           f"INDICATORS PRESENT. {adversary} may have left orbit. Escalate.")
    else:
        verdict = tool.get("pass_message",
                           f"No trace of {adversary} in these entries. He remains in space.")
    out += ["", f"verdict: {verdict}",
            "note: this tool is a stub. It confirms the entries reached it and does a string scan; "
            "the analysis behind this interface is yours to build."]
    return "\n".join(out), False


BEHAVIORS = {
    "static": b_static, "echo": b_echo, "template": b_template,
    "forbidden_words": b_forbidden_words, "required_words": b_required_words,
    "regex_check": b_regex_check, "word_count": b_word_count, "always_error": b_always_error,
    "gravwell_grep_hoist": b_gravwell_grep_hoist, "threat_hunt": b_threat_hunt,
}


# ======================================================================== config
DEFAULT_SCHEMA = {"type": "object",
                  "properties": {"text": {"type": "string", "description": "the text to check"}},
                  "required": ["text"], "additionalProperties": False}


def load_config(path):
    if tomllib is None:
        raise SystemExit("this needs Python 3.11+ (for tomllib); found " + sys.version.split()[0])
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        raise SystemExit(f"config not found: {path}")
    except tomllib.TOMLDecodeError as e:
        raise SystemExit(f"{path} is not valid TOML:\n  {e}\n\n"
                         "Common causes: a missing closing quote, a stray tab, or a multi-line\n"
                         'string that needs triple quotes ("""like this""").')


def validate(cfg):
    """Return a list of human-readable problems. Empty list means the config is usable."""
    errs, warns = [], []
    srv = cfg.get("server", {})
    if not srv.get("name"):
        errs.append("[server] needs a `name`: this is what the client displays.")
    if "WRITE ME" in (srv.get("instructions") or ""):
        warns.append("[server] instructions still says WRITE ME.")
    seen = set()
    tools = cfg.get("tools", [])
    if not tools and not cfg.get("prompts") and not cfg.get("resources"):
        warns.append("this config declares no tools, prompts or resources: the server will start "
                     "but offer nothing.")
    for i, t in enumerate(tools):
        where = f"[[tools]] #{i + 1}" + (f" ({t['name']})" if t.get("name") else "")
        if not t.get("name"):
            errs.append(f"{where} needs a `name`.")
        elif t["name"] in seen:
            errs.append(f"{where}: duplicate tool name {t['name']!r}.")
        else:
            seen.add(t["name"])
        if not t.get("description"):
            warns.append(f"{where} has no `description`. The model reads the description to decide "
                         "whether to call the tool: an undescribed tool is nearly invisible to it.")
        placeholders = ("WRITE ME" in (t.get("description") or "")) + sum(
            "WRITE ME" in str(p.get("description", ""))
            for p in ((t.get("input_schema") or {}).get("properties") or {}).values())
        if placeholders:
            warns.append(f"{where}: {placeholders} WRITE ME placeholder(s) still in place. The server "
                         "will run, but the model will read the placeholder text, not instructions.")
        beh = t.get("behavior", "static")
        if beh not in BEHAVIORS:
            errs.append(f"{where}: unknown behavior {beh!r}. Valid: {', '.join(sorted(BEHAVIORS))}.")
        if beh in ("forbidden_words", "required_words") and not t.get("words"):
            errs.append(f"{where}: behavior {beh!r} needs a `words = [...]` list.")
        if beh == "regex_check" and not t.get("pattern"):
            errs.append(f"{where}: behavior 'regex_check' needs a `pattern`.")
    for i, p in enumerate(cfg.get("prompts", [])):
        if not p.get("name"):
            errs.append(f"[[prompts]] #{i + 1} needs a `name`.")
        if not p.get("text"):
            errs.append(f"[[prompts]] #{i + 1} ({p.get('name','?')}) needs `text`.")
    for i, r in enumerate(cfg.get("resources", [])):
        if not r.get("uri"):
            errs.append(f"[[resources]] #{i + 1} needs a `uri`.")
    return errs, warns


# ======================================================================== protocol logging
class Sink:
    """Writes one JSON object per line: every message in and out. This is the audit trail of your
    own MCP server, and it is the same idea as the logging proxy in Lab 05."""

    def __init__(self, path=None, tcp=None, stderr=False):
        self.f = open(path, "a", buffering=1) if path else None
        self.stderr, self.sock = stderr, None
        if tcp:
            host, _, port = tcp.rpartition(":")
            try:
                self.sock = socket.create_connection((host, int(port)), timeout=5)
            except OSError as e:
                print(f"[mcp-lab] warning: could not connect to {tcp}: {e}", file=sys.stderr)

    def log(self, direction, msg, session=None, server=None):
        rec = {"ts": now(), "direction": direction, "session_id": session, "server": server,
               "method": msg.get("method"), "id": msg.get("id"), "message": msg}
        line = json.dumps(rec)
        if self.f:
            self.f.write(line + "\n")
        if self.stderr:
            if direction == "call":
                print(f"[mcp-lab] call {msg.get('tool')} arguments={json.dumps(msg.get('arguments'))}",
                      file=sys.stderr)
            else:
                print(f"[mcp-lab] {direction:3} {msg.get('method') or 'result'}", file=sys.stderr)
        if self.sock:
            try:
                self.sock.sendall((line + "\n").encode())
            except OSError:
                self.sock = None


# ======================================================================== the server
class LabServer:
    def __init__(self, cfg, sink):
        self.cfg, self.sink = cfg, sink
        self.srv = cfg.get("server", {})
        self.name = self.srv.get("name", "mcp-lab-server")

    # -- MCP manifests, built straight from the config -------------------------------------
    def _tools(self):
        out = []
        for t in self.cfg.get("tools", []):
            out.append({"name": t["name"],
                        "description": t.get("description", ""),
                        "inputSchema": t.get("input_schema") or DEFAULT_SCHEMA})
        return out

    def _prompts(self):
        return [{"name": p["name"], "description": p.get("description", ""),
                 "arguments": p.get("arguments", [])} for p in self.cfg.get("prompts", [])]

    def _resources(self):
        return [{"uri": r["uri"], "name": r.get("name", r["uri"]),
                 "description": r.get("description", ""),
                 "mimeType": r.get("mime_type", "text/plain")}
                for r in self.cfg.get("resources", [])]

    # -- dispatch --------------------------------------------------------------------------
    def handle(self, msg, session=None):
        """Returns a JSON-RPC response dict, or None for notifications."""
        mid, method, params = msg.get("id"), msg.get("method"), msg.get("params") or {}

        def ok(result):
            return {"jsonrpc": "2.0", "id": mid, "result": result}

        def err(code, message):
            return {"jsonrpc": "2.0", "id": mid, "error": {"code": code, "message": message}}

        if method == "initialize":
            caps = {"tools": {"listChanged": False}}
            if self.cfg.get("prompts"):
                caps["prompts"] = {"listChanged": False}
            if self.cfg.get("resources"):
                caps["resources"] = {"listChanged": False}
            res = {"protocolVersion": PROTOCOL_VERSION, "capabilities": caps,
                   "serverInfo": {"name": self.name,
                                  "version": str(self.srv.get("version", "1.0.0"))}}
            if self.srv.get("instructions"):
                res["instructions"] = self.srv["instructions"]
            return ok(res)

        if method in ("notifications/initialized", "notifications/cancelled", "ping"):
            return ok({}) if method == "ping" and mid is not None else None

        if method == "tools/list":
            return ok({"tools": self._tools()})

        if method == "prompts/list":
            return ok({"prompts": self._prompts()})

        if method == "resources/list":
            return ok({"resources": self._resources()})

        if method == "tools/call":
            name, args = params.get("name"), params.get("arguments") or {}
            tool = next((t for t in self.cfg.get("tools", []) if t.get("name") == name), None)
            if tool is None:
                return err(INVALID_PARAMS, f"no such tool: {name!r}. "
                                           f"Offered: {', '.join(t['name'] for t in self._tools())}")
            schema = tool.get("input_schema") or DEFAULT_SCHEMA
            missing = [r for r in schema.get("required", []) if r not in args]
            if missing:
                return err(INVALID_PARAMS,
                           f"missing required argument(s): {', '.join(missing)}")
            if schema.get("additionalProperties") is False:
                extra = [k for k in args if k not in (schema.get("properties") or {})]
                if extra:
                    return err(INVALID_PARAMS,
                               f"unexpected argument(s): {', '.join(extra)}")
            # One explicit record per accepted call: the tool and the arguments exactly as they
            # arrived. Everything in `arguments` was put there by the model, and any of it may be
            # another server's tool result relayed through the model (Lab 07: `parse_result` is
            # Gravwell's parse_query output, verbatim). This is the line that proves it.
            self.sink.log("call", {"tool": name, "arguments": args}, session, self.name)
            fn = BEHAVIORS.get(tool.get("behavior", "static"), b_static)
            try:
                text, is_error = fn(tool, args)
            except Exception as e:                                     # a broken config, not a crash
                text, is_error = f"tool raised {type(e).__name__}: {e}", True
            return ok({"content": [{"type": "text", "text": text}], "isError": bool(is_error)})

        if method == "prompts/get":
            name = params.get("name")
            p = next((x for x in self.cfg.get("prompts", []) if x.get("name") == name), None)
            if p is None:
                return err(INVALID_PARAMS, f"no such prompt: {name!r}")
            text = p["text"]
            for k, v in (params.get("arguments") or {}).items():
                text = text.replace("{" + k + "}", str(v))
            return ok({"description": p.get("description", ""),
                       "messages": [{"role": p.get("role", "user"),
                                     "content": {"type": "text", "text": text}}]})

        if method == "resources/read":
            uri = params.get("uri")
            r = next((x for x in self.cfg.get("resources", []) if x.get("uri") == uri), None)
            if r is None:
                return err(INVALID_PARAMS, f"no such resource: {uri!r}")
            return ok({"contents": [{"uri": uri, "mimeType": r.get("mime_type", "text/plain"),
                                     "text": r.get("text", "")}]})

        return err(METHOD_NOT_FOUND, f"this server does not implement {method!r}")


# ======================================================================== transports
def serve_stdio(server, sink):
    """Newline-delimited JSON-RPC on stdin/stdout, what opencode spawns.

    NOTHING may go to stdout except protocol messages; diagnostics go to stderr or the log."""
    session = "stdio-" + uuid.uuid4().hex[:8]
    print(f"[mcp-lab] {server.name} on stdio (session {session})", file=sys.stderr)
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            out = {"jsonrpc": "2.0", "id": None,
                   "error": {"code": PARSE_ERROR, "message": "invalid JSON"}}
            sink.log("in", {"raw": line[:400]}, session, server.name)
            sys.stdout.write(json.dumps(out) + "\n"); sys.stdout.flush()
            continue
        sink.log("in", msg, session, server.name)
        resp = server.handle(msg, session)
        if resp is not None:
            sink.log("out", resp, session, server.name)
            sys.stdout.write(json.dumps(resp) + "\n"); sys.stdout.flush()


def serve_http(server, sink, bind):
    """Streamable HTTP on one endpoint: the same shape you curled in Lab 06."""
    host, _, port = bind.rpartition(":")
    sessions = set()

    class H(BaseHTTPRequestHandler):
        protocol_version = "HTTP/1.1"

        def log_message(self, *a):
            pass

        def _send(self, code, obj, extra=None):
            body = json.dumps(obj).encode()
            self.send_response(code)
            self.send_header("content-type", "application/json")
            self.send_header("content-length", str(len(body)))
            for k, v in (extra or {}).items():
                self.send_header(k, v)
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            self._send(200, {"server": server.name, "transport": "streamable-http",
                             "endpoint": "POST /", "tools": [t["name"] for t in server._tools()]})

        def do_POST(self):
            n = int(self.headers.get("content-length", 0))
            raw = self.rfile.read(n) if n else b"{}"
            try:
                msg = json.loads(raw or b"{}")
            except json.JSONDecodeError:
                return self._send(400, {"jsonrpc": "2.0", "id": None,
                                        "error": {"code": PARSE_ERROR, "message": "invalid JSON"}})
            sid = self.headers.get("Mcp-Session-Id")
            extra = {}
            if msg.get("method") == "initialize":
                sid = uuid.uuid4().hex[:26].upper()
                sessions.add(sid)
                extra["Mcp-Session-Id"] = sid
            sink.log("in", msg, sid, server.name)
            resp = server.handle(msg, sid)
            if resp is None:
                self.send_response(202); self.send_header("content-length", "0")
                for k, v in extra.items():
                    self.send_header(k, v)
                return self.end_headers()
            sink.log("out", resp, sid, server.name)
            self._send(200, resp, extra)

    httpd = ThreadingHTTPServer((host or "0.0.0.0", int(port)), H)
    print(f"[mcp-lab] {server.name} on http://{host or '0.0.0.0'}:{port} "
          f"({len(server._tools())} tools)", file=sys.stderr)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[mcp-lab] stopped", file=sys.stderr)


# ======================================================================== main
def main():
    ap = argparse.ArgumentParser(description="A config-driven MCP server for learning MCP.")
    ap.add_argument("--config", required=True, help="TOML file describing the server")
    ap.add_argument("--http", metavar="HOST:PORT",
                    help="serve streamable HTTP instead of stdio (e.g. 0.0.0.0:1491)")
    ap.add_argument("--log-file", help="append every JSON-RPC message here as JSONL")
    ap.add_argument("--tcp", metavar="HOST:PORT",
                    help="also ship messages as newline JSON over TCP (e.g. a Gravwell listener)")
    ap.add_argument("--verbose", action="store_true", help="echo message names to stderr")
    ap.add_argument("--validate", action="store_true", help="check the config and exit")
    ap.add_argument("--version", action="version", version=f"mcp_lab_server {VERSION}")
    a = ap.parse_args()

    cfg = load_config(a.config)
    errs, warns = validate(cfg)
    for w in warns:
        print(f"[mcp-lab] warning: {w}", file=sys.stderr)
    if errs:
        print(f"\n{len(errs)} problem(s) in {a.config}:", file=sys.stderr)
        for e in errs:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(2)

    if a.validate:
        srv = cfg.get("server", {})
        print(f"OK: {a.config}")
        print(f"  server:    {srv.get('name')} v{srv.get('version', '1.0.0')}")
        print(f"  tools:     {len(cfg.get('tools', []))}")
        for t in cfg.get("tools", []):
            print(f"               - {t['name']}  ({t.get('behavior', 'static')})")
        print(f"  prompts:   {len(cfg.get('prompts', []))}")
        print(f"  resources: {len(cfg.get('resources', []))}")
        return

    sink = Sink(a.log_file, a.tcp, a.verbose)
    server = LabServer(cfg, sink)
    if a.http:
        serve_http(server, sink, a.http)
    else:
        serve_stdio(server, sink)


if __name__ == "__main__":
    main()
